version: '3.8'

services:
  db:
    image: postgres:15
    container_name: modbot-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: modbot
    ports:
      - "5432:5432"
    volumes:
      - modbot-data:/var/lib/postgresql/data
      # tells Docker to runschema automatically on a fresh install
      - ./db/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql 

volumes:
  modbot-data: